airports = [
    'Warsaw',
    'Amsterdam',
    'Gdańsk',
    'Radom',
    'Berlin',
    'Paris',
    'New York',
    'Sydney',
    'Boston',
    'Washington DC',
    'New Orlean',
    'Rome',
    'London',
    'Yrkuck',
    'Los Angeles',
    'Tokio',
    'Bern',
    'Kabul',
    'Tirana',
    'Algiers',
    'Andorra la Vella',
    'Luanda',
    'Saint John\'s',
    'Buenos Aires',
    'Yerevan',
    'Canberra',
    'Vienna',
    'Baku',
    'Nassau',
    'Manama',
    'Dhaka',
    'Bridgetown',
    'Minsk',
    'Brussels',
    'Belmopan',
    'Porto-Novo',
    'Thimphu',
    'Sarajevo',
    'Gaborone',
    'Brasilia',
    'Bandar Seri Begawan',
    'Sofia',
    'Ouagadougou',
    'Bujumbura',
    'Praia',
    'Phnom Penh',
    'Yaounde',
    'Ottawa',
    'Bangui',
    'N\'Djamena',
    'Santiago',
    'Beijing',
    'Bogotá',
    'Moroni',
    'Kinshasa',
    'Brazzaville',
    'San Jose',
    'Yamoussoukro',
    'Zagreb',
    'Havana',
    'Nicosia',
    'Prague',
    'Copenhagen',
    'Roseau',
    'Santo Domingo',
    'Quito',
    'Cairo',
    'San Salvador',
    'Asmara',
    'Tallinn',
    'Addis Ababa',
    'Suva',
    'Helsinki',
    'Paris',
    'Libreville',
    'Banjul',
    'Tbilisi',
    'Berlin',
    'Accra',
    'Athens',
    'Saint George\'s',
    'Guatemala City',
    'Conakry',
    'Bissau',
    'Georgetown',
    'Port-au-Prince',
    'Tegucigalpa',
    'Budapest',
    'Reykjavik',
    'New Delhi',
    'Jakarta',
    'Tehran',
    'Baghdad',
    'Dublin',
    'Jerusalem',
    'Rome',
    'Kingston',
    'Tokyo',
    'Amman',
    'Astana',
    'Nairobi',
    'Tarawa',
    'Pristina',
    'Kuwait City',
    'Bishkek',
    'Vientiane',
    'Riga',
    'Beirut',
    'Maseru',
    'Monrovia',
    'Tripoli',
    'Vaduz',
    'Vilnius',
    'Luxembourg',
    'Abu Dhabi',
    'London',
    'Washington, D.C.',
    'Montevideo',
    'Tashkent',
    'Port Vila',
    'Vatican City',
    'Caracas',
    'Hanoi',
    'Sana\'a',
    'Lusaka',
    'Harare',
    'Seoul',
    'Juba',
    'Madrid',
    'Sri Jayawardenepura Kotte',
    'Khartoum',
    'Paramaribo',
    'Stockholm',
    'Bern',
    'Damascus',
    'Taipei',
    'Dushanbe',
    'Dodoma',
    'Bangkok',
    'Dili',
    'Lomé',
    'Nukuʻalofa',
    'Port of Spain',
    'Tunis',
    'Ankara',
    'Ashgabat',
    'Funafuti',
    'Kampala',
    'Kathmandu',
    'Amsterdam',
    'Wellington',
    'Managua',
    'Niamey',
    'Abuja',
    'Pyongyang',
    'Oslo',
    'Muscat',
    'Islamabad',
    'Ngerulmud',
    'Jerusalem (East)',
    'Panama City',
    'Port Moresby',
    'Asunción',
    'Lima',
    'Manila',
    'Warsaw',
    'Lisbon',
    'Doha',
    'Bucharest',
    'Moscow',
    'Kigali',
    'Basseterre',
    'Castries',
    'Kingstown',
    'Apia',
    'San Marino',
    'São Tomé',
    'Riyadh',
    'Dakar',
    'Belgrade',
    'Victoria',
    'Freetown',
    'Singapore',
    'Bratislava',
    'Ljubljana',
    'Honiara',
    'Mogadishu',
    'Skopje',
    'Antananarivo',
    'Lilongwe',
    'Kuala Lumpur',
    'Male',
    'Bamako',
    'Valletta',
    'Majuro',
    'Nouakchott',
    'Port Louis',
    'Mexico City',
    'Palikir',
    'Chisinau',
    'Monaco',
    'Ulaanbaatar',
    'Podgorica',
    'Rabat',
    'Maputo',
    'Naypyidaw',
    'Windhoek'
]
