# Generated by Django 2.0.5 on 2018-06-15 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlines.Crew'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='airlines.Plane'),
        ),
    ]
