# Generated by Django 2.0.2 on 2018-05-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0003_auto_20180505_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='flight',
            name='tickets',
            field=models.ManyToManyField(blank=True, null=True, to='airlines.User'),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
