# Generated by Django 2.0.2 on 2018-05-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0005_auto_20180505_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tickets',
        ),
        migrations.AddField(
            model_name='flight',
            name='tickets',
            field=models.ManyToManyField(blank=True, null=True, to='airlines.User'),
        ),
    ]
