# Generated by Django 2.0.2 on 2018-05-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0006_auto_20180505_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flights',
            field=models.ManyToManyField(blank=True, null=True, to='airlines.Flight'),
        ),
    ]
