# Generated by Django 2.0.2 on 2018-05-06 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0007_user_flights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='airlines.Plane'),
        ),
    ]
