# Generated by Django 2.0.5 on 2018-05-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0008_auto_20180506_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='reg_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='Registration identificator'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('surname', 'name')},
        ),
    ]
