# Generated by Django 2.0.5 on 2018-05-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0009_auto_20180512_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='tickets',
            field=models.ManyToManyField(blank=True, to='airlines.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='flights',
            field=models.ManyToManyField(blank=True, to='airlines.Flight'),
        ),
    ]
