# Generated by Django 2.0.5 on 2018-05-16 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0010_auto_20180512_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_id', models.CharField(max_length=15, verbose_name='Crew ID')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='crew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airlines.Crew'),
        ),
    ]
