# Generated by Django 2.0.5 on 2018-05-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0011_auto_20180516_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('crew', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airlines.Crew')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together={('surname', 'name')},
        ),
    ]
